//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int blogID { get; set; }
        public int userID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string tag { get; set; }
        public string img { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual user user { get; set; }
    }
}
