//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingID { get; set; }
        public int userID { get; set; }
        public int roomID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> numberOfGuest { get; set; }
        public Nullable<double> total { get; set; }
        public string status { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string requests { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual room room { get; set; }
        public virtual user user { get; set; }
    }
}
