//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatPhongKhachSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingHotel1Entities2 : DbContext
    {
        public BookingHotel1Entities2()
            : base("name=BookingHotel1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<restaurant> restaurants { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
